# Generated by Django 4.1.6 on 2023-02-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cause",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                ("orgSchool", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=50)),
                ("date", models.DateField(max_length=50)),
                ("targetAmount", models.IntegerField(max_length=10)),
            ],
        ),
    ]
