# Generated by Django 4.1.6 on 2023-02-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bpFund", "0002_alter_cause_targetamount"),
    ]

    operations = [
        migrations.AddField(
            model_name="cause",
            name="contribNum",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cause",
            name="problem",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="cause",
            name="sol",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
